apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-config
  namespace: default
data:
  LANG: en_US.UTF-8
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: enabled
  RAILS_SERVE_STATIC_FILES: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-api
  labels:
    name: application-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: application-api
  template:
    metadata:
      labels:
        name: application-api
    spec:
      containers:
        - name: web
          envFrom:
          - configMapRef:
              name: rails-config
          - secretRef:
              name: rails-secret
          image: GCP_REGISTRY/GKE_PROJECT/IMAGE:TAG
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /_health
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_health
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
