apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.global-static-ip-name: global-loadbalancer
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: service-api
              servicePort: 3000
