apiVersion: v1
kind: Service
metadata:
  name: service-api
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    name: application-api
  type: NodePort
