default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode

  host: 127.0.0.1
  username: postgres
  password: password

development:
  <<: *default
  database: application_api_development

test:
  <<: *default
  database: application_api_test

production:
  url: <%= ENV['DATABASE_URL'] %>
