name: Deploy to Endpoints

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: ${{ github.repository }}
  GKE_LOCATION: us-central1
  GKE_CLUSTER: gke-us-central1
  REGISTRY_HOSTNAME: us.gcr.io
  DEPLOYMENT_NAME: application-api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}

      - name: Deploy
        run: |
          gcloud endpoints services deploy openapi.yaml
