name: Deploy to GKE

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: ${{ github.repository }}
  GKE_LOCATION: us-central1
  GKE_CLUSTER: gke-us-central1
  REGISTRY_HOSTNAME: us.gcr.io
  DEPLOYMENT_NAME: application-api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}

      - run: |
          gcloud auth configure-docker

      - name: Set up Kustomize
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_LOCATION --project $GKE_PROJECT
          ./kustomize edit set image GCP_REGISTRY/GKE_PROJECT/IMAGE:TAG=$REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
